"""FastAPI application and endpoints."""

from src.api.exceptions import (
    APIException,
    AuthenticationException,
    AuthorizationException,
    ExportException,
    InvalidRequestException,
    QualityAssessmentException,
    RateLimitException,
    ReportGenerationException,
    ReportNotFoundException,
    ServiceUnavailableException,
)
from src.api.models import (
    DeleteReportResponse,
    DetailedReportResponse,
    ErrorResponse,
    ExportFormat,
    ExportRequest,
    ExportResponse,
    HealthResponse,
    ListReportsRequest,
    ListReportsResponse,
    QualityAssessmentRequest,
    QualityAssessmentResponse,
    QualityDimensionResponse,
    QualityIssueResponse,
    ReportGenerationRequest,
    ReportResponse,
    ReportStatus,
    SectionSummary,
)

__all__ = [
    # Exceptions
    "APIException",
    "ReportNotFoundException",
    "InvalidRequestException",
    "ReportGenerationException",
    "QualityAssessmentException",
    "ExportException",
    "ServiceUnavailableException",
    "RateLimitException",
    "AuthenticationException",
    "AuthorizationException",
    # Models
    "ReportGenerationRequest",
    "ReportStatus",
    "ReportResponse",
    "SectionSummary",
    "DetailedReportResponse",
    "QualityAssessmentRequest",
    "QualityDimensionResponse",
    "QualityIssueResponse",
    "QualityAssessmentResponse",
    "ExportFormat",
    "ExportRequest",
    "ExportResponse",
    "HealthResponse",
    "ErrorResponse",
    "ListReportsRequest",
    "ListReportsResponse",
    "DeleteReportResponse",
]
